name: Python scripts

on:
  push:
    branches: ["master"]
    paths:
     - "scripts/**"
     - ".github/workflows/scripts.yml"
  pull_request:
    branches: ["master"]
    paths:
     - "scripts/**"
     - ".github/workflows/scripts.yml"

jobs:
  check-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r scripts/requirements.txt

      - name: Check MyPy
        run: python3 -m mypy scripts

      - name: Check Black
        run: python3 -m black --check scripts
